/* Main.c file generated by New Project wizard
 *
 * Created:   ma. ene. 28 2025
 * Processor: MSP430F2491
 * Compiler:  CodeComposer for MSP430
 */

#define CPU_MSP430x241


#include "T:\Workspaces\Headers\msp430f2491.h"
#include "T:\Workspaces\Headers\OLED_driver.h" // Make sure you have the correct library for controlling the OLED


 // Function prototypes for OLED operations
void oled_init(void);
void oled_clear(void);
void oled_printChar(char, int, int);

void initI2C() {
    // Configure pins 44 and 45 for I2C
    P4SEL |= BIT4 | BIT5; // Assign alternate functions for I2C
    UCB1CTL1 |= UCSWRST;   // Put USCI_B1 in reset
    UCB1CTL0 = UCMST | UCMODE_3 | UCSYNC; // I2C Master, synchronous mode
    UCB1CTL1 = UCSSEL_2 | UCSWRST; // Use SMCLK as the clock source
    UCB1BR0 = 10; // Set clock prescaler
    UCB1BR1 = 0;
    UCB1CTL1 &= ~UCSWRST; // Release from reset
}

int main(void) {  // Change from 'void main(void)' to 'int main(void)'
    WDTCTL = WDTPW | WDTHOLD;   // Stop the watchdog timer
    initI2C(); // Initialize I2C configuration
    oled_init(); // Initialize the OLED display
    oled_clear(); // Clear the display
    oled_printChar('1', 0, 0); // Print the character '1' at position (0,0)

    while (1) {
        // Keep the MCU in low power mode or perform other tasks
        __bis_SR_register(LPM0_bits + GIE); // Enter low power mode 0 with interrupts enabled
    }

    return 0;  // Return 0 to indicate successful execution
}
